<?php
class scoober_api
{
    private $accestoken;   
    private $headers; 
    function _construct($username,$password)
    {
        $this->username = $username;
        $this->password = $password;
        // $this->accestoken = $this->_login();
        $this->accestoken = "493c74795eb74003a54f8eb7e618f65f08f41a0712b6407f812a4ee79c3af7b5";
        // $this->headers = $this->get_headers();
    }

    /**
     * work around for getting all the headers
     *
     * @return object of headers 
     */
    private function get_headers(){
        $headers = array();
        $headers[] = 'Host: shiftplanning-api.scoober.com';
        $headers[] = 'Cookie: __cf_bm=UVta3Mc3OgMJzzFqgsnrBHLtuKbmqx7UD59.2m1qj4c-1642805815-0-AXnBSQSeFaY0xspiZ1ZWL0TYUa/vQg9hExC04zAS7c1zl0e0qiirXvDKgSK1Nf3StBW3Np3lKaDiGeaDjvq0tfApvSwRSgCJA1i+SSONmppC';
        $headers[] = 'Accept: */*';
        $headers[] = 'Content-Type: application/json';
        $headers[] = 'Accept-Language: en-NL;q=1.0, nl-NL;q=0.9, de-NL;q=0.8, ru-NL;q=0.7';
        $headers[] = 'Agent: ios-app-v2.17.0';
        $headers[] = 'If-None-Match: W/\"2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w\"';
        $headers[] = 'User-Agent: Scoober/2.17.0 (com.takeaway.scoober; build:20211103.121233; iOS 15.2.1) Alamofire/5.4.3';
        $headers[] = "Accesstoken: " . $this->accestoken;
        return $headers;
    }

    function get_schedule()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        // i know its bad but sue me 
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://shiftplanning-api.scoober.com/api/users/plannings?fromDate=2022-01-24&toDate=2022-01-30');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        curl_setopt($ch, CURLOPT_HTTPHEADER, $this->get_headers());

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;
    }

    function get_open_shifts()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://shiftplanning-api.scoober.com/api/openshift?fromDate=2022-01-24&toDate=2022-01-30');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = $this->get_headers();
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
    }

    /**
     * gets a acces token via email and password combo
     *
     * @return void
     */
    function _login()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.scoober.com/v2/login');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"password\":\"ysb8v4MbebpHX6a6\",\"userName\":\"constantijn@vanhartesveldt.nl\"}");
        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = $this->get_headers();
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;
    }
}
